import { gql, useQuery } from '@apollo/client';
import Head from 'next/head'
import { useEffect } from 'react';

export const PRODUCTS_QUERY = gql`
  query GetProductList {
    products {
      id
      name
      price
      description
    }
  }
`;

const PRODUCTS_SUBSCRIPTION = gql`
  subscription newProduct {
    newProduct {
      id
      name
      price
      description
    }
  }
`;

interface Product {
  id?: string;
  title?: string;
  price?: number;
  image: string;
  description?: string;
}

export default function Apollo() {
  const { data, loading, subscribeToMore } = useQuery(
    PRODUCTS_QUERY
  );

  useEffect(() => {
    subscribeToMore && subscribeToMore({
      document: PRODUCTS_SUBSCRIPTION,
      updateQuery: (prev, { subscriptionData }) => {
        if (!subscriptionData.data) {
          return prev;
        }

        return Object.assign({}, prev, {
          products: [subscriptionData.data.newProduct, ...prev.products],
        });
      },
    });
  }, [subscribeToMore]);

  return (
    <>
      <Head>
        <title>Home App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="" style={{}}>
        <div className="bg-white">
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 className="text-2xl font-bold tracking-tight text-gray-900">
              Product List graphql (Query + Subscription)
            </h2>
            <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {data?.products?.map((product: Product) => (
                <div className="group relative" key={product.id}>
                  <div className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
                    <img
                      src={
                        product.image ||
                        "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg"
                      }
                      alt={product.name}
                      className="h-full w-full object-cover object-center lg:h-full lg:w-full"
                    />
                  </div>
                  <div className="mt-4 flex justify-between">
                    <div>
                      <h3 className="text-sm text-gray-700">
                        <a href="#">
                          <span
                            aria-hidden="true"
                            className="absolute inset-0"
                          />
                          {product.name}
                        </a>
                      </h3>
                      <p className="mt-1 text-sm text-gray-500">Black</p>
                    </div>
                    <p className="text-sm font-medium text-gray-900">
                      {product.price}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
