import Head from 'next/head'
import { useEffect, useState } from 'react';
import { io } from "socket.io-client";

interface Product {
  id?: string;
  title?: string;
  price?: number;
  image: string;
  description?: string;
}

const socket = io("ws://localhost:4001/");

export default function Rest() {
  const [data, setData] = useState<Product[]>([]);

  useEffect(() => {
    fetch("http://localhost:4001/product", {
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
    })
      .then((v) => v.json())
      .then(setData);

    console.log("newProduct:", typeof window);

    socket.on("newProduct", (p: Product) => {
      setData((pre) => [p, ...pre]);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Home App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="" style={{}}>
        <div className="bg-white">
          <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 className="text-2xl font-bold tracking-tight text-gray-900">
              Product List (Rest Full + Socket.Io)
            </h2>
            <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
              {data?.map((product) => (
                <div className="group relative" key={product.id}>
                  <div className="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
                    <img
                      src={
                        product.image ||
                        "https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg"
                      }
                      alt={product.name}
                      className="h-full w-full object-cover object-center lg:h-full lg:w-full"
                    />
                  </div>
                  <div className="mt-4 flex justify-between">
                    <div>
                      <h3 className="text-sm text-gray-700">
                        <a href="#">
                          <span
                            aria-hidden="true"
                            className="absolute inset-0"
                          />
                          {product.name}
                        </a>
                      </h3>
                      <p className="mt-1 text-sm text-gray-500">Black</p>
                    </div>
                    <p className="text-sm font-medium text-gray-900">
                      {product.price}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
